<?php
$pageTitle='Library Reports'; require __DIR__.'/config/database.php'; require __DIR__.'/includes/header.php';
$summary=['Titles'=>(int)$pdo->query("SELECT COUNT(*) FROM books WHERE status='active'")->fetchColumn(),'Total Copies'=>(int)$pdo->query("SELECT COALESCE(SUM(total_copies),0) FROM books WHERE status='active'")->fetchColumn(),'Available'=>(int)$pdo->query("SELECT COALESCE(SUM(available_copies),0) FROM books WHERE status='active'")->fetchColumn(),'Members'=>(int)$pdo->query("SELECT COUNT(*) FROM members WHERE status='active'")->fetchColumn(),'Issued'=>(int)$pdo->query("SELECT COUNT(*) FROM loans WHERE status='issued'")->fetchColumn(),'Overdue'=>(int)$pdo->query("SELECT COUNT(*) FROM loans WHERE status='issued' AND due_date<CURDATE()")->fetchColumn(),'Returned'=>(int)$pdo->query("SELECT COUNT(*) FROM loans WHERE status='returned'")->fetchColumn(),'Lost'=>(int)$pdo->query("SELECT COUNT(*) FROM loans WHERE status='lost'")->fetchColumn()];
$issued=$pdo->query("SELECT l.*,b.title,m.member_code,m.name FROM loans l JOIN books b ON b.id=l.book_id JOIN members m ON m.id=l.member_id WHERE l.status='issued' ORDER BY l.due_date")->fetchAll();
$overdue=$pdo->query("SELECT l.*,b.title,m.member_code,m.name FROM loans l JOIN books b ON b.id=l.book_id JOIN members m ON m.id=l.member_id WHERE l.status='issued' AND l.due_date<CURDATE() ORDER BY l.due_date")->fetchAll();
$popular=$pdo->query("SELECT b.title,COUNT(l.id) borrow_count FROM loans l JOIN books b ON b.id=l.book_id GROUP BY b.id,b.title ORDER BY borrow_count DESC LIMIT 10")->fetchAll();
$fine=(float)$pdo->query("SELECT COALESCE(SUM(fine_amount),0) FROM loans")->fetchColumn(); ?>
<h2>Library Reports</h2><div class="row g-3 mb-4"><?php foreach($summary as $k=>$v): ?><div class="col-6 col-md-3 col-lg"><div class="card shadow-sm"><div class="card-body"><div class="small text-muted"><?=h($k)?></div><div class="fs-4 fw-bold"><?=$v?></div></div></div></div><?php endforeach; ?></div>
<div class="alert alert-info"><strong>Total recorded fines:</strong> ₹<?=number_format($fine,2)?></div>
<h5>Currently Issued Books</h5><div class="table-responsive"><table class="table table-striped"><thead><tr><th>Member</th><th>Book</th><th>Issue Date</th><th>Due Date</th></tr></thead><tbody><?php foreach($issued as $x): ?><tr><td><?=h($x['member_code'].' - '.$x['name'])?></td><td><?=h($x['title'])?></td><td><?=h($x['issue_date'])?></td><td><?=h($x['due_date'])?></td></tr><?php endforeach; ?></tbody></table></div>
<h5 class="mt-4">Overdue Books</h5><div class="table-responsive"><table class="table table-danger table-striped"><thead><tr><th>Member</th><th>Book</th><th>Due Date</th><th>Days</th></tr></thead><tbody><?php foreach($overdue as $x): ?><tr><td><?=h($x['member_code'].' - '.$x['name'])?></td><td><?=h($x['title'])?></td><td><?=h($x['due_date'])?></td><td><?=max(0,(int)((strtotime(date('Y-m-d'))-strtotime($x['due_date']))/86400))?></td></tr><?php endforeach; ?></tbody></table></div>
<h5 class="mt-4">Most Borrowed Books</h5><div class="table-responsive"><table class="table table-striped"><thead><tr><th>Book</th><th>Times Borrowed</th></tr></thead><tbody><?php foreach($popular as $x): ?><tr><td><?=h($x['title'])?></td><td><?=$x['borrow_count']?></td></tr><?php endforeach; ?></tbody></table></div>
<?php require __DIR__.'/includes/footer.php';